[package]
name = "beam"
version = "0.1.0"
authors = ["Kezenator <github@kezenator.com>"]
edition = "2018"

[dependencies]
float-ord = { version = "0.3.0" }
rand = { version = "0.8.3", features = ["small_rng"] }
rayon = { version = "1.5.0" }
sdl2 = { version = "0.34.3", features = ["bundled", "static-link"] }
winapi = { version = "0.3.9", features = ["std", "shellscalingapi"] }
vek = { version = "0.15.0" }
